export const ERROR_CODES = {
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",

  TEST_CASE_NOT_FOUND: "TEST_CASE_NOT_FOUND",

  TEST_RUN_NOT_FOUND: "TEST_RUN_NOT_FOUND",

  TEST_SUITE_NOT_FOUND: "TEST_SUITE_NOT_FOUND",

  TAG_NOT_FOUND: "TAG_NOT_FOUND",

  RUN_BATCH_NOT_FOUND: "RUN_BATCH_NOT_FOUND",

  HISTORY_NOT_FOUND: "HISTORY_NOT_FOUND",

  INVALID_API_KEY: "INVALID_API_KEY",

  API_KEY_EXPIRED: "API_KEY_EXPIRED",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  PERMISSION_DENIED: "PERMISSION_DENIED",

  UNAUTHORIZED: "UNAUTHORIZED",

  SYNC_FAILED: "SYNC_FAILED",

  TRACE_UPLOAD_FAILED: "TRACE_UPLOAD_FAILED",

  REPORTER_UPLOAD_FAILED: "REPORTER_UPLOAD_FAILED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
