export const HISTORY_ACTIONS = {
  CREATED: "CREATED",

  UPDATED: "UPDATED",

  RESTORED: "RESTORED",

  STALE: "STALE",

  STATUS_CHANGED: "STATUS_CHANGED",

  MANUAL_OVERRIDE: "MANUAL_OVERRIDE",

  MANUAL_OVERRIDE_CLEARED: "MANUAL_OVERRIDE_CLEARED",
} as const;

export type HistoryAction =
  (typeof HISTORY_ACTIONS)[keyof typeof HISTORY_ACTIONS];