services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: assertive
      POSTGRES_PASSWORD: assertive
      POSTGRES_DB: assertive

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
